1. Import NumPy and create arrays

In [1]:
import numpy as np

# 1D array
a = np.array([1, 2, 3])
print(a)

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)


[1 2 3]
[[1 2 3]
 [4 5 6]]


2. Shape and size

In [2]:
print(a.shape)   # (3,)
print(b.shape)   # (2,3)

(3,)
(2, 3)


3. Basic operations

In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)      # element-wise addition
print(x * y)      # element-wise multiplication
print(np.dot(x,y))# dot product


[5 7 9]
[ 4 10 18]
32


4. Broadcasting

In [4]:
m = np.array([[1,2,3],[4,5,6]])
print(m + 10)   # adds 10 to every element


[[11 12 13]
 [14 15 16]]


Write a function that computes the cosine similarity between two vectors

In [6]:
def cosine_sim(a, b):

    dot = np.dot(a,b)

    normA = np.linalg.norm(a)
    normB = np.linalg.norm(b)

    answer = dot / (normA * normB)

    return answer

# Test

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print(cosine_sim(v1,v2))

print(cosine_sim(v1,np.array([2,4,6])))
print(cosine_sim(v1,np.array([0,1,0])))

0.9746318461970762
1.0
0.5345224838248488


[1,2,3] and [2,4,6] are collinear (one is just a scaled version of the other). That’s why their cosine similarity is 1.0 (perfectly aligned). Meanwhile [0,1,0] points in a totally different direction, so the similarity is much lower.

That’s the core idea: in AI, embeddings (like text vectors) are “similar” if they point in the same direction, not if they have the same length.